name: Hexalith Application Build
on:
  push:
    paths-ignore:
      - '**/*.md'
      - 'mkdocs.yml'
      - 'docs/**/*'
    branches: 
      - main
      - release-*
    tags:
      - 'v*'
  pull_request:
    branches: 
      - master
      - release-*
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Build, Test, Publish
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Add Android Workload
      run: |
        dotnet workload install android
    - name: Add Ios Workload
      run: |
        dotnet workload install ios
    - name: Add Mac Catalyst Workload
      run: |
        dotnet workload install maccatalyst
    - name: Add Maui Workload
      run: |
        dotnet workload install maui
    - name: Build Version
      run: |
        dotnet tool install --global minver-cli --version 5.0.0
        version=$(minver -t v -v e -d preview)
        echo "MINVERVERSIONOVERRIDE=$version" >> $GITHUB_ENV
        echo "VERSION=$version" >> $GITHUB_ENV
        echo "VERSION=$version"
    - name: Build
      run: |
    - name: Build
      run: |
        dotnet build './src/HexalithApp.Client/HexalithApp.Client.csproj' --configuration Release -p:Version=${{ env.VERSION }}
        dotnet build './src/HexalithApp.Server/HexalithApp.Server.csproj' --configuration Release -p:Version=${{ env.VERSION }}
        dotnet build './src/HexalithApp.Shared/HexalithApp.Shared.csproj' --configuration Release -p:Version=${{ env.VERSION }}
        dotnet build './src/HexalithApp.StoreApp/HexalithApp.StoreApp.csproj' --configuration Release -p:Version=${{ env.VERSION }}
    - name: Unit Tests
      run: |
        dotnet test -c Release --no-restore --no-build ./test/HexalithApp.UnitTests/HexalithApp.UnitTests.csproj 